spring.application.name=order-service
server.port=8082
jwt.secret=smartpay_secret_smartpay_secret_12345

#db config 
spring.datasource.url=jdbc:mysql://localhost:3307/smartpay_orders
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
